FROM dairyisscary/circleci:latest

RUN apk -v --update --no-cache add bash

ENV TERRAFORM_VERSION=0.11.3
RUN wget -O terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" && \
  unzip terraform.zip -d /bin && \
  rm -rf terraform.zip
